<?php

namespace Proxies\__CG__\GOL\ContentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \GOL\ContentBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'id', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'name', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'image', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'phone', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'email', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'profile', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'profession', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby1', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby2', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby3', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent1', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent2', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent3'];
        }

        return ['__isInitialized__', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'id', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'name', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'image', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'phone', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'email', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'profile', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'profession', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby1', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby2', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'hobby3', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent1', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent2', '' . "\0" . 'GOL\\ContentBundle\\Entity\\Profile' . "\0" . 'percent3'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile($profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setHobby1($hobby1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHobby1', [$hobby1]);

        return parent::setHobby1($hobby1);
    }

    /**
     * {@inheritDoc}
     */
    public function getHobby1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHobby1', []);

        return parent::getHobby1();
    }

    /**
     * {@inheritDoc}
     */
    public function setHobby2($hobby2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHobby2', [$hobby2]);

        return parent::setHobby2($hobby2);
    }

    /**
     * {@inheritDoc}
     */
    public function getHobby2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHobby2', []);

        return parent::getHobby2();
    }

    /**
     * {@inheritDoc}
     */
    public function setHobby3($hobby3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHobby3', [$hobby3]);

        return parent::setHobby3($hobby3);
    }

    /**
     * {@inheritDoc}
     */
    public function getHobby3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHobby3', []);

        return parent::getHobby3();
    }

    /**
     * {@inheritDoc}
     */
    public function getPercent1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercent1', []);

        return parent::getPercent1();
    }

    /**
     * {@inheritDoc}
     */
    public function getPercent2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercent2', []);

        return parent::getPercent2();
    }

    /**
     * {@inheritDoc}
     */
    public function getPercent3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercent3', []);

        return parent::getPercent3();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercent1($percent1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercent1', [$percent1]);

        return parent::setPercent1($percent1);
    }

    /**
     * {@inheritDoc}
     */
    public function setPercent2($percent2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercent2', [$percent2]);

        return parent::setPercent2($percent2);
    }

    /**
     * {@inheritDoc}
     */
    public function setPercent3($percent3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercent3', [$percent3]);

        return parent::setPercent3($percent3);
    }

}
